build-webview: allow richer arguments to `err`
Allow multple arguments and arguments containing '\n'.

diff --git a/tools/build-webview b/tools/build-webview
--- a/tools/build-webview
+++ b/tools/build-webview
@@ -25,7 +25,7 @@ EOF
 
 # print error and die
 err() {
-    echo "$0:" $'\e[31merror:\e[0m' "$1" >&2
+    echo -e "$0:" $'\e[31merror:\e[0m' "$@" >&2
     exit 1;
 }
 
