test: Add `tsflower` suite, checking definitions up to date and patches clean

diff --git a/tools/test b/tools/test
--- a/tools/test
+++ b/tools/test
@@ -63,6 +63,7 @@ Suites:
   jest
   prettier
   deps
+  tsflower
 EOF
     exit 2
 }
@@ -87,7 +88,7 @@ while (( $# )); do
             ;;
         --all) files=all; platform=both; shift;;
         --fix) fix=1; shift;;
-        native|flow|lint|jest|prettier|deps)
+        native|flow|lint|jest|prettier|deps|tsflower)
             suites+=("$1"); shift;;
         *) usage;;
     esac
@@ -96,7 +97,7 @@ done
 if [ -z "$suites" ]; then
     # This default doesn't have to be the complete list; just be sure to
     # document in the usage message any suites that it skips.
-    suites=(native flow lint jest prettier deps)
+    suites=(native flow lint jest prettier deps tsflower)
 fi
 
 
@@ -252,6 +253,26 @@ EOF
     fi
 }
 
+run_tsflower() {
+    # This suite depends on:
+    #  * the tools/tsflower script
+    #  * the type definitions in types/**/*.js.flow
+    #  * the patches in types/patches/*.patch
+    #  * the versions of `tsflower` and of libraries it processes
+    files_check tools/tsflower types/ yarn.lock \
+        || return 0
+
+    # NB this suite will fail (with a reasonable error message) if
+    # there are any local Git changes, because it can't do its work
+    # without making changes to the worktree.  (Short of making a
+    # temporary worktree somewhere, anyway; but that'd probably mean a
+    # slow test suite.)  Hopefully in normal development this is fine:
+    # it usually won't run because of files_check; if it does, the
+    # error message comes fast and is short, and doesn't get in the
+    # way of the other suites doing their jobs.
+    tools/tsflower check
+}
+
 failed=()
 for suite in "${suites[@]}"; do
     echo "Running $suite..."
@@ -273,6 +294,9 @@ for suite in "${suites[@]}"; do
             ;;
         deps)
             run_deps
+            ;;
+        tsflower)
+            run_tsflower
             ;;
     esac || failed+=($suite)
 done
diff --git a/tools/tsflower b/tools/tsflower
--- a/tools/tsflower
+++ b/tools/tsflower
@@ -85,6 +85,35 @@ write_patches()
         -o "${patch_dir}" "${commit_range}"
 }
 
+check_consistent()
+{
+    if ! no_uncommitted_changes; then
+        echo >&2 "There are uncommitted changes.  Aborting, to avoid losing your work."
+        return 1
+    fi
+
+    unapply_patches
+
+    # TODO: also catch if one patch touches something and another reverts
+    if ! git diff --exit-code HEAD -- ':!types/*.js.flow'; then
+        echo >&2 "Error: patches should only apply to type definitions in types/."
+        return 1
+    fi
+    echo >&2 "Patches are clean.  Running TsFlower..."
+
+    git add -u
+
+    run_only
+
+    if ! git diff --exit-code; then
+        echo >&2 "Error: fresh TsFlower run didn't match existing definitions"
+        return 1
+    fi
+    echo >&2 "TsFlower run successful."
+
+    git reset --hard --quiet
+}
+
 check_branch_unused()
 {
     local branchname="$1"
@@ -222,11 +251,7 @@ EOF
 
 
 case "${1:-}" in
-    # TODO: subcmd `check`: unapply; check limited to types/**/*.js.flow;
-    #   then restore those files.  Probably needs to skip if any such file
-    #   already touched in Git. ... Also run, and check no changes?
-    #   Then tools/test run this if types/ or yarn.lock touched.
-
+    check) check_consistent;;
     run) run;;  # TODO also as default
     run-only) run_only;;
     apply-patches) apply_patches;;
